import Banner from "@/components/Banner";
import PageHeader from "@/components/PageHeader";
import Card from "@/components/products/Card";
import Teams from "@/components/Teams";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pakan Ternak</title>
        <meta name="description" content="Generated by Pakan Ternak" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner />

      <PageHeader
        title="Pakan Ternak Sapi"
        description="Dijamin sapi anda pasti akan kenyang dan juga sehat. karna makanan ini
        mengandung zat energi super yang bisa membuat sapi 20x lebih kuat dari
        sebelumya."
      />

      <Card />

      <PageHeader
        title="Team Kami"
        description="Ini adalah sekumpulan orang-orang keren, yang mau membantu orang yang membutuhkan pangan segala ternak melata, dilaut maupun di luar angkasa"
      />

      <Teams />
    </>
  );
}
