import Banner from "@/components/Banner";
import PageHeader from "@/components/PageHeader";
import Card from "@/components/products/Card";
import Head from "next/head";
import Image from "next/image";
import Goni from "../../public/img/pakan-goni.jpeg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pakan Ternak</title>
        <meta name="description" content="Generated by Pakan Ternak" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner />

      <PageHeader />

      <Card />
    </>
  );
}
